Repository rigetti/pennylane-forest, pull requests merged in 2020-02, with the labels that each got.

#39 Adding parametric compilation for QVM and QPU
  doc/conf.py
  pennylane_forest/device.py
  pennylane_forest/qpu.py
  pennylane_forest/qvm.py
  setup.py
  tests/test_converter.py
  tests/test_device.py
  tests/test_numpy_wavefunction.py
  tests/test_pyqvm.py
  tests/test_qpu.py
  tests/test_qvm.py
  tests/test_wavefunction.py
Labels: enhancement, review-ready

#41 Testing single observable Tensor operator estimation, mutual exclusion with parametric compilation
  pennylane_forest/qpu.py
  pennylane_forest/qvm.py
  tests/test_pyqvm.py
  tests/test_qpu.py
  tests/test_qvm.py
Labels: bug

#44 Bump version number and update requirements
  pennylane_forest/_version.py
  pennylane_forest/device.py
  requirements.txt
  setup.py
Labels: review-ready

#42 Adding support for multi-qubit observable estimation
  pennylane_forest/qpu.py
  tests/test_qpu.py
Labels: review-ready

#46 Add gradient test
  tests/test_converter.py
Labels: tests
